#[embassy_executor::task]
async fn morse(speed: u64, text: &'static str, mut buzzer: Output<'static>) {


    let short_beep: u64 = 1200 / speed;
    let long_beep: u64 = 3 * short_beep;

    loop {
        for letter in text.chars() {
            match letter {
                'a' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'b' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'c' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'd' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'e' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'f' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'g' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'h' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'i' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'j' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'k' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'l' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'm' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'n' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'o' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'p' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'q' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'r' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                's' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                't' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'u' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'v' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'w' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'x' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'y' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                'z' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                '0' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                '1' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                '2' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                '3' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                '4' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                '5' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                '6' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                '7' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                '8' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                '9' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                '?' => {
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(long_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_high();
                    Timer::after(Duration::from_millis(short_beep)).await;
                    buzzer.set_low();
                    Timer::after(Duration::from_millis(long_beep)).await
                },
                ' ' => {
                    Timer::after(Duration::from_millis(500)).await;
                }
                _ => Timer::after(Duration::from_millis(1)).await
            }
        }
    }
}